name: baideshikrojgar
description: A new Flutter project.


version: 3.0.23+53

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  get: 3.23.1
  nice_button: ^0.1.7
  awesome_dialog: ^1.3.1
  audio_service: ^0.16.2+1
  flutter_easyloading: ^2.2.2
  http: ^0.12.2
  package_info: ^0.4.0+16
  flutter_slidable:
  flutter_html: ^1.0.0
  url_launcher: ^5.5.0
  share:
  cached_network_image: ^2.2.0+1
  flutter_facebook_login: ^3.0.0
  carousel_slider: ^3.0.0
  flutter_countdown_timer: ^3.0.1
  multi_select_flutter: ^3.1.8
  flutter_signin_button: ^1.1.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  google_sign_in: ^4.5.9
  sign_in_with_apple: ^2.5.4
  shimmer: ^1.1.2
  apple_sign_in: ^0.1.0
  flutter_rating_bar:
  connectivity: ^2.0.2
  textfield_tags: ^1.1.1
  shared_preferences: ^0.5.12+4
  just_audio: ^0.6.15+1
  flutter_tts: ^2.1.0
  device_info:
  permission_handler:
  google_mobile_ads: ^0.11.0
  google_maps_flutter:
  onesignal_flutter: ^2.6.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: "^0.7.3"
flutter_launcher_name:
  name: "Baideshik Rojgar"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
